-- Artemis Embed v1 document retrieval schema
-- Vector dimension is fixed at 256 for the current document index.

create extension if not exists vector with schema extensions;
create extension if not exists pgcrypto with schema extensions;

create table if not exists public.documents (
    id uuid primary key default gen_random_uuid(),
    name text not null,
    storage_path text not null unique,
    mime_type text not null,
    size_bytes bigint not null check (size_bytes >= 0),
    status text not null default 'processing' check (status in ('processing', 'ready', 'error')),
    chunk_count integer not null default 0 check (chunk_count >= 0),
    created_at timestamptz not null default now()
);

create table if not exists public.document_chunks (
    id bigint generated by default as identity primary key,
    document_id uuid not null references public.documents(id) on delete cascade,
    chunk_index integer not null,
    content text not null,
    embedding extensions.vector(256) not null,
    created_at timestamptz not null default now(),
    unique (document_id, chunk_index)
);

create index if not exists document_chunks_document_id_idx
    on public.document_chunks(document_id);

create index if not exists document_chunks_embedding_hnsw_idx
    on public.document_chunks
    using hnsw (embedding extensions.vector_cosine_ops);

insert into storage.buckets (id, name, public)
values ('artemis-documents', 'artemis-documents', false)
on conflict (id) do nothing;

create or replace function public.match_document_chunks(
    query_embedding extensions.vector(256),
    match_count integer default 5,
    filter_document_id uuid default null
)
returns table (
    id bigint,
    document_id uuid,
    chunk_index integer,
    content text,
    score double precision
)
language sql
stable
as $$
    select
        dc.id,
        dc.document_id,
        dc.chunk_index,
        dc.content,
        1 - (dc.embedding <=> query_embedding) as score
    from public.document_chunks dc
    where filter_document_id is null or dc.document_id = filter_document_id
    order by dc.embedding <=> query_embedding
    limit greatest(1, least(match_count, 20));
$$;

alter table public.documents enable row level security;
alter table public.document_chunks enable row level security;

-- No anonymous policies are created intentionally. The Vercel FastAPI backend
-- uses the server-only service role key as the access boundary.
